name: Test Minimal Reusable

on:
  workflow_dispatch:

jobs:
  build_kumiki:
    uses: minimapletinytools/kumiki/.github/workflows/publish.yml@main
    with:
      target: testpypi
      publish: false
      tag: kumiki-v0.3.1
